#include "ShaderGenerator.h"
#include <fstream>
#include <stdexcept>

#include "BufferInterfaceBlock.h"
#include "SamplerInterfaceBlock.h"
#include "ShaderInputBuilder.h"
#include "TemplateProvider.h"
#include "UibGenerator.h"

std::string ShaderGenerator::LoadTemplate(const std::string& name) const {
	std::string p = m_TemplateDir + "/" + name;
	std::ifstream f(p, std::ios::binary);
	if (!f.is_open()) throw std::runtime_error("cannot open template: " + p);
	std::string c((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
	if (c.size()>=3 && (unsigned char)c[0]==0xEF && (unsigned char)c[1]==0xBB && (unsigned char)c[2]==0xBF) c.erase(0,3);
	size_t pos=0; while((pos=c.find("\r\n",pos))!=std::string::npos) c.erase(pos,1);
	return c;
}

static const char* ToString(MaterialDomain d) {
	switch(d){case MaterialDomain::SURFACE:return"surface";case MaterialDomain::POST_PROCESS:return"postprocess";case MaterialDomain::COMPUTE:return"compute";}
	return"unknown";
}

void ShaderGenerator::EmitHeader(std::ostringstream& os, CodeGenerator& cg, const MaterialSpec& spec) const {
	os << "// Auto-generated by matc -- Material: "<<spec.name<<"\n// Domain: "<<ToString(spec.domain)<<"\n// Shading: "<<spec.shadingModel<<"\n\n";
	os << "#version 460\n\n"<<LoadTemplate("surface_types.glsl")<<'\n';
	cg.generateUniforms(os, UIB::GetPerViewUIB()); cg.generateUniforms(os, UIB::GetPerRenderableUIB());
	if (!spec.materialUib.isEmpty()) cg.generateUniforms(os, spec.materialUib);
	if (!spec.materialSib.isEmpty()) cg.generateCommonSamplers(os, spec.materialSib);
	os << "// Feature macros\n"; cg.generateVaryingDefines(os, spec); cg.generateConstantDefines(os, spec); cg.generateAttributeDefines(os, spec); cg.generatePropertyDefines(os, spec);
	os << "#define SHADING_MODEL_ID "<<(spec.shadingModel=="lit"?1:0)<<"\n\n";
}
void ShaderGenerator::EmitLightHeader(std::ostringstream& os) const {
	os << "// Auto-generated by matc\n\n#version 460\n\n"<<LoadTemplate("surface_types.glsl")<<'\n';
}
void ShaderGenerator::EmitVertexInputs(std::ostringstream& os, const MaterialSpec& spec) const {
	auto inputs = BuildVertexInputs(spec);
	for (auto& v : inputs) os << "layout(location="<<(int)v.location<<") in vec4 "<<v.name<<";\n";
	os<<'\n';
}
void ShaderGenerator::EmitVaryingOut(std::ostringstream& os) const { auto c=LoadTemplate("surface_varying.glsl"); os<<"#define VARYING out\n"<<c<<'\n'; }
void ShaderGenerator::EmitVaryingIn(std::ostringstream& os) const  { auto c=LoadTemplate("surface_varying.glsl"); os<<"#define VARYING in\n"<<c<<'\n'; }
void ShaderGenerator::EmitFragmentOutputs(std::ostringstream& os, const MaterialSpec& spec) const {
	if (spec.outputs.empty()) return;
	os<<"// Fragment outputs\n"; int ci=0;
	for (auto& o:spec.outputs){if(o.type=="color")os<<"layout(location="<<ci++<<") out vec4 "<<o.name<<";\n";else if(o.type=="depth")os<<"layout(depth_any) out float "<<o.name<<";\n";}
	os<<'\n';
}

std::string ShaderGenerator::MainTemplate(Stage stage, Pass pass, Pipeline pipeline) const {
	if (stage==Stage::Vertex){switch(pass){case Pass::Depth:return"surface_depth_main.vs";case Pass::GBuffer:return pipeline==Pipeline::FORWARD?"surface_forward_main.vs":"surface_deferred_main.vs";case Pass::Lighting:return"surface_shading_main.vs";}}
	else{switch(pass){case Pass::Depth:return"surface_depth_main.fs";case Pass::GBuffer:return pipeline==Pipeline::FORWARD?"surface_forward_main.fs":"surface_deferred_main.fs";case Pass::Lighting:return"surface_shading_main.fs";}}
	return{};
}

ShaderGenerator::ShaderGenerator(MaterialBuilder::PropertyList const& props,
	MaterialBuilder::VariableList const& vars, MaterialBuilder::OutputList const& outs,
	MaterialBuilder::PreprocessorDefineList const& defs, MaterialBuilder::PushConstantList const& pcs,
	std::string const& matCode, size_t lineOff, std::string const& vertCode, size_t vertLineOff,
	MaterialBuilder::MaterialDomain dom)
	: m_Defines(defs), m_PushConstants(pcs), m_MaterialLineOffset(lineOff),
	  m_MaterialVertexCode(vertCode), m_MaterialVertexLineOffset(vertLineOff), m_MaterialDomain(dom)
{
	std::copy(std::begin(props),std::end(props),std::begin(m_Properties));
	std::copy(std::begin(vars),std::end(vars),std::begin(m_Variables));
	std::copy(std::begin(outs),std::end(outs),std::back_inserter(m_Outputs));
	m_MaterialFragmentCode=matCode; m_MaterialVertexCode=vertCode; m_IsMaterialVertexShaderEmpty=vertCode.empty();
	if (m_MaterialFragmentCode.empty()){if(m_MaterialDomain==MaterialBuilder::MaterialDomain::SURFACE)m_MaterialFragmentCode="void material(inout MaterialInputs m){\n    prepareMaterial(m);\n}\n";else if(m_MaterialDomain==MaterialBuilder::MaterialDomain::POST_PROCESS)m_MaterialFragmentCode="void postProcess(inout PostProcessInputs p){\n}\n";else if(m_MaterialDomain==MaterialBuilder::MaterialDomain::COMPUTE)m_MaterialFragmentCode="void compute(){\n}\n";}
	if (m_MaterialVertexCode.empty()){if(m_MaterialDomain==MaterialBuilder::MaterialDomain::SURFACE)m_MaterialVertexCode="void materialVertex(inout MaterialVertexInputs m){\n}\n";else if(m_MaterialDomain==MaterialBuilder::MaterialDomain::POST_PROCESS)m_MaterialVertexCode="void postProcessVertex(inout PostProcessVertexInputs m){\n}\n";}
}

std::string ShaderGenerator::GenerateShader(Stage stage, Pass pass, const MaterialSpec& spec, const std::string& code) const {
	switch(stage){case Stage::Vertex:switch(pass){case Pass::Depth:return GenDepthVS(spec,code);case Pass::GBuffer:return GenGBufferVS(spec,code);case Pass::Lighting:return GenLightingVS(spec,code);}break;
	case Stage::Fragment:switch(pass){case Pass::Depth:return GenDepthFS(spec,code);case Pass::GBuffer:return GenGBufferFS(spec,code);case Pass::Lighting:return GenLightingFS(spec,code);}break;
	case Stage::Compute:return GenerateComputeShader(spec,code);}return{};
}
std::string ShaderGenerator::GeneratePostProcessShader(Stage stage, const MaterialSpec& spec, const std::string& code) const {
	switch(stage){case Stage::Vertex:return GenPostProcessVS(spec,code);case Stage::Fragment:return GenPostProcessFS(spec,code);default:return{};}
}

std::string ShaderGenerator::GenDepthVS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec); os<<'\n';
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define VERTEX_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'<<LoadTemplate("common_math.glsl")<<'\n';
	EmitVertexInputs(os,spec); EmitVaryingOut(os);
	for(auto& f:Provider::GetDepthVertex())os<<LoadTemplate(f)<<'\n';
	os<<LoadTemplate("common_getter.glsl")<<'\n'; cg.generateVaryingDeclarations(os,spec,"out");
	if(!code.empty())os<<"// User vertex code\n"<<code<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Vertex,Pass::Depth,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenDepthFS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define FRAGMENT_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'; EmitVaryingIn(os);
	os<<LoadTemplate("surface_material_input.fs")<<'\n'<<LoadTemplate("surface_instancing.glsl")<<'\n';
	if(!code.empty())os<<"// User fragment code\n"<<code<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Fragment,Pass::Depth,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenGBufferVS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec); os<<'\n';
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define VERTEX_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'<<LoadTemplate("common_math.glsl")<<'\n';
	EmitVertexInputs(os,spec); EmitVaryingOut(os);
	for(auto& f:Provider::GetGBufferVertex())os<<LoadTemplate(f)<<'\n';
	os<<LoadTemplate("common_getter.glsl")<<'\n'; cg.generateVaryingDeclarations(os,spec,"out");
	if(!code.empty())os<<"// User vertex code\n"<<code<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Vertex,Pass::GBuffer,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenGBufferFS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define FRAGMENT_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'<<LoadTemplate("common_math.glsl")<<'\n'<<LoadTemplate("common_shading.glsl")<<'\n';
	EmitVaryingIn(os);
	os<<LoadTemplate("surface_instancing.glsl")<<'\n'<<LoadTemplate("surface_material_input.fs")<<'\n';
	{auto c=LoadTemplate("surface_getters.fs");if(!c.empty())os<<c<<'\n';}
	os<<LoadTemplate("common_getter.glsl")<<'\n'<<LoadTemplate("surface_shading_parameters.fs")<<'\n';
	cg.generateVaryingDeclarations(os,spec,"in"); EmitFragmentOutputs(os,spec);
	if(!code.empty())os<<"// User fragment code\n"<<code<<'\n';
	os<<LoadTemplate("surface_shading_"+spec.shadingModel+".fs")<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Fragment,Pass::GBuffer,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenLightingVS(const MaterialSpec& spec, const std::string&) const {
	std::ostringstream os; EmitLightHeader(os);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define VERTEX_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Vertex,Pass::Lighting,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenLightingFS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define LIGHTING_PASS\n#define FRAGMENT_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'<<LoadTemplate("common_math.glsl")<<'\n'<<LoadTemplate("common_shading.glsl")<<'\n';
	os<<LoadTemplate("surface_material_input.fs")<<'\n'<<LoadTemplate("lighting_uniforms.glsl")<<'\n';
	os<<LoadTemplate("surface_shading_parameters.fs")<<'\n';
	if(!code.empty())os<<"// User fragment code\n"<<code<<'\n';
	os<<LoadTemplate("surface_shading_unlit.fs")<<'\n'<<LoadTemplate("surface_shading_lit.fs")<<'\n';
	os<<LoadTemplate(MainTemplate(Stage::Fragment,Pass::Lighting,spec.pipeline))<<'\n'; return os.str();
}
std::string ShaderGenerator::GenPostProcessVS(const MaterialSpec& spec, const std::string&) const {
	std::ostringstream os; EmitLightHeader(os);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define VERTEX_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n';
	for(auto& f:Provider::GetPostProcessVertex())os<<LoadTemplate(f)<<'\n';
	os<<LoadTemplate("post_process_main.vs")<<'\n'; return os.str();
}
std::string ShaderGenerator::GenPostProcessFS(const MaterialSpec& spec, const std::string& code) const {
	std::ostringstream os; CodeGenerator cg; EmitHeader(os,cg,spec);
	if(m_TargetVulkan)os<<"#define TARGET_VULKAN_ENVIRONMENT\n";os<<"#define FRAGMENT_STAGE\n\n";
	os<<LoadTemplate("common_defines.glsl")<<'\n'<<LoadTemplate("common_math.glsl")<<'\n';
	os<<LoadTemplate("post_process_inputs.fs")<<'\n';
	if(!code.empty())os<<"// User fragment code\n"<<code<<'\n';
	os<<LoadTemplate("post_process_main.fs")<<'\n'; return os.str();
}
std::string ShaderGenerator::GenerateComputeShader(const MaterialSpec&, const std::string&) const { return {}; }
