#include "ShaderGenerator.h"

#include <fstream>
#include <stdexcept>

#include "BufferInterfaceBlock.h"
#include "SamplerInterfaceBlock.h"
#include "ShaderInputBuilder.h"
#include "UibGenerator.h"

// =============================================================================
// Template loading
// =============================================================================

std::string ShaderGenerator::LoadTemplate(const std::string& name) const
{
	std::string path = m_TemplateDir + "/" + name;
	std::ifstream f(path, std::ios::binary);
	if (!f.is_open())
		throw std::runtime_error("cannot open template file: " + path);

	std::string content((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());

	if (content.size() >= 3 &&
		(unsigned char)content[0] == 0xEF &&
		(unsigned char)content[1] == 0xBB &&
		(unsigned char)content[2] == 0xBF)
		content.erase(0, 3);

	size_t pos = 0;
	while ((pos = content.find("\r\n", pos)) != std::string::npos)
		content.erase(pos, 1);

	return content;
}

// =============================================================================
// Shared header
// =============================================================================

static const char* ToString(MaterialDomain domain)
{
	switch (domain)
	{
	case MaterialDomain::SURFACE:      return "surface";
	case MaterialDomain::POST_PROCESS: return "postprocess";
	case MaterialDomain::COMPUTE:      return "compute";
	}
	return "unknown";
}

void ShaderGenerator::EmitHeader(std::ostringstream& os, CodeGenerator& cg,
                                 const MaterialSpec& spec) const
{
	os << "// =====================================================\n";
	os << "// Auto-generated by matc -- Material: " << spec.name << "\n";
	os << "// Domain: " << ToString(spec.domain) << "\n";
	os << "// Shading model: " << spec.shadingModel << "\n";
	os << "// =====================================================\n\n";

	os << "#version 460\n\n";

	os << LoadTemplate("surface_types.glsl") << '\n';

	auto & perViewUib = UIB::GetPerViewUIB();
	if (!perViewUib.isEmpty())
		cg.generateUniforms(os, perViewUib);

	if (spec.pipeline != Pipeline::LIGHTING)
	{
		auto & perRenderableUib = UIB::GetPerRenderableUIB();
		if (!perRenderableUib.isEmpty())
			cg.generateUniforms(os, perRenderableUib);
	}

	if (!spec.materialUib.isEmpty())
		cg.generateUniforms(os, spec.materialUib);

	if (!spec.materialSib.isEmpty())
		cg.generateCommonSamplers(os, spec.materialSib);

	os << "// Feature macros for conditional compilation\n";
	cg.generateVaryingDefines(os, spec);
	cg.generateConstantDefines(os, spec);
	cg.generateAttributeDefines(os, spec);
	cg.generatePropertyDefines(os, spec);

	int shadingModelId = (spec.shadingModel == "lit") ? 1 : 0;
	os << "#define SHADING_MODEL_ID " << shadingModelId << "\n";
	os << '\n';
}

// =============================================================================
// Vertex shader
// =============================================================================

std::string ShaderGenerator::GenerateVertexShader(
	const MaterialSpec& spec,
	const std::string& expandedVertexCode) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg, spec);

	// Lighting / PostProcess: simple full-screen quad
	if (spec.pipeline == Pipeline::LIGHTING || spec.domain == MaterialDomain::POST_PROCESS)
	{
		os << "#define VERTEX_STAGE\n\n";
		os << LoadTemplate("common_defines.glsl") << '\n';
		os << LoadTemplate("surface_shading_main.vs") << '\n';
		return os.str();
	}

	if (spec.domain == MaterialDomain::SURFACE)
		os << "#define VERTEX_DOMAIN_DEVICE\n";
	os << '\n';

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define VERTEX_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';

	{
		os << "// Vertex input attributes\n";
		auto inputs = BuildVertexInputs(spec);
		for (auto& v : inputs)
			os << "layout(location = " << (int)v.location << ") in vec4 " << v.name << ";\n";
		os << '\n';
	}

	os << LoadTemplate("surface_builtins.glsl") << '\n';

	{
		auto content = LoadTemplate("surface_varying.glsl");
		os << "#define VARYING out\n";
		os << content << '\n';
	}

	os << LoadTemplate("surface_instancing.glsl") << '\n';

	{
		auto content = LoadTemplate("surface_getters.vs");
		if (!content.empty()) os << content << '\n';
	}

	os << LoadTemplate("surface_material_input.vs") << '\n';
	os << LoadTemplate("common_getter.glsl") << '\n';
	cg.generateVaryingDeclarations(os, spec, "out");

	if (!expandedVertexCode.empty())
		os << "// User vertex code\n" << expandedVertexCode << '\n';

	{
		std::string file = "surface_" + std::string(spec.pipeline == Pipeline::DEFERRED ? "deferred" : "forward") + "_main.vs";
		os << LoadTemplate(file) << '\n';
	}

	return os.str();
}

// =============================================================================
// Fragment shader
// =============================================================================

std::string ShaderGenerator::GenerateFragmentShader(
	const MaterialSpec& spec,
	const std::string& expandedFragmentCode) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg, spec);

	// Lighting / PostProcess: read GBuffer + compute lighting, output single color
	if (spec.pipeline == Pipeline::LIGHTING || spec.domain == MaterialDomain::POST_PROCESS)
	{
		if (m_TargetVulkan)
			os << "#define TARGET_VULKAN_ENVIRONMENT\n";
		os << "#define LIGHTING_PASS\n";
		os << "#define FRAGMENT_STAGE\n\n";

		os << LoadTemplate("common_defines.glsl") << '\n';
		os << LoadTemplate("common_math.glsl") << '\n';
		os << LoadTemplate("common_shading.glsl") << '\n';
		os << LoadTemplate("surface_material_input.fs") << '\n';
		os << LoadTemplate("lighting_uniforms.glsl") << '\n';
		os << LoadTemplate("surface_shading_parameters.fs") << '\n';

		if (!expandedFragmentCode.empty())
			os << "// User fragment code\n" << expandedFragmentCode << '\n';

		os << LoadTemplate("surface_shading_unlit.fs") << '\n';
		os << LoadTemplate("surface_shading_lit.fs") << '\n';
		os << LoadTemplate("surface_shading_main.fs") << '\n';
		return os.str();
	}

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define FRAGMENT_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';

	os << LoadTemplate("common_shading.glsl") << '\n';

	{
		auto content = LoadTemplate("surface_varying.glsl");
		os << "#define VARYING in\n";
		os << content << '\n';
	}

	os << LoadTemplate("surface_instancing.glsl") << '\n';
	os << LoadTemplate("surface_material_input.fs") << '\n';
	os << LoadTemplate("surface_builtins.glsl") << '\n';

	{
		auto content = LoadTemplate("surface_getters.fs");
		if (!content.empty()) os << content << '\n';
	}

	os << LoadTemplate("common_getter.glsl") << '\n';
	os << LoadTemplate("surface_shading_parameters.fs") << '\n';
	cg.generateVaryingDeclarations(os, spec, "in");

	if (!spec.outputs.empty())
	{
		os << "// Fragment outputs\n";
		int colorIndex = 0;
		for (const auto& o : spec.outputs)
		{
			if (o.type == "color")
				os << "layout(location = " << colorIndex++ << ") out vec4 " << o.name << ";\n";
			else if (o.type == "depth")
				os << "layout(depth_any) out float " << o.name << ";\n";
		}
		os << '\n';
	}

	if (!expandedFragmentCode.empty())
		os << "// User fragment code\n" << expandedFragmentCode << '\n';

	os << LoadTemplate("surface_shading_" + spec.shadingModel + ".fs") << '\n';

	{
		std::string file = "surface_" + std::string(spec.pipeline == Pipeline::DEFERRED ? "deferred" : "forward") + "_main.fs";
		os << LoadTemplate(file) << '\n';
	}

	return os.str();
}
