#include "ShaderGenerator.h"

#include <fstream>
#include <stdexcept>

#include "BufferInterfaceBlock.h"
#include "SamplerInterfaceBlock.h"
#include "ShaderInputBuilder.h"
#include "TemplateProvider.h"
#include "UibGenerator.h"

// =============================================================================
// Template loading
// =============================================================================

std::string ShaderGenerator::LoadTemplate(const std::string& name) const
{
	std::string path = m_TemplateDir + "/" + name;
	std::ifstream f(path, std::ios::binary);
	if (!f.is_open())
		throw std::runtime_error("cannot open template: " + path);

	std::string content((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());

	if (content.size() >= 3 &&
		(unsigned char)content[0] == 0xEF &&
		(unsigned char)content[1] == 0xBB &&
		(unsigned char)content[2] == 0xBF)
	{
		content.erase(0, 3);
	}

	size_t pos = 0;
	while ((pos = content.find("\r\n", pos)) != std::string::npos)
		content.erase(pos, 1);

	return content;
}

// =============================================================================
// Shared headers
// =============================================================================

static const char* ToString(MaterialDomain domain)
{
	switch (domain)
	{
	case MaterialDomain::SURFACE:      return "surface";
	case MaterialDomain::POST_PROCESS: return "postprocess";
	case MaterialDomain::COMPUTE:      return "compute";
	}
	return "unknown";
}

void ShaderGenerator::EmitHeader(std::ostringstream& os, CodeGenerator& cg) const
{
	os << "// Auto-generated by matc -- Material: " << m_MaterialName << "\n";
	os << "// Domain: " << ToString(m_MaterialDomain) << "\n";
	os << "#version 460\n\n";
	os << LoadTemplate("surface_types.glsl") << '\n';

	cg.generateUniforms(os, UIB::GetPerViewUIB());
	cg.generateUniforms(os, UIB::GetPerRenderableUIB());

	if (m_MaterialUib && !m_MaterialUib->isEmpty())
		cg.generateUniforms(os, *m_MaterialUib);
	if (m_MaterialSib && !m_MaterialSib->isEmpty())
		cg.generateCommonSamplers(os, *m_MaterialSib);

	os << "// Feature macros for conditional compilation\n";
	cg.generateVaryingDefines(os, m_Variables);
	cg.generateConstantDefines(os, m_Defines);
	cg.generateAttributeDefines(os, m_RequiredAttributes);
	cg.generatePropertyDefines(os, m_Properties);

	int shadingModelId = m_ShadingModel == Shading::LIT;
	os << "#define SHADING_MODEL_ID " << shadingModelId << "\n\n";
}

void ShaderGenerator::EmitLightHeader(std::ostringstream& os) const
{
	os << "// Auto-generated by matc\n\n";
	os << "#version 460\n\n";
	os << LoadTemplate("surface_types.glsl") << '\n';
}

// =============================================================================
// Shared emitters
// =============================================================================

void ShaderGenerator::EmitVertexInputs(std::ostringstream& os) const
{
	auto inputs = BuildVertexInputs(m_MaterialDomain, m_RequiredAttributes);
	for (auto& v : inputs)
		os << "layout(location = " << (int)v.location << ") in vec4 " << v.name << ";\n";
	os << '\n';
}

void ShaderGenerator::EmitVaryingOut(std::ostringstream& os) const
{
	auto content = LoadTemplate("surface_varying.glsl");
	os << "#define VARYING out\n" << content << '\n';
}

void ShaderGenerator::EmitVaryingIn(std::ostringstream& os) const
{
	auto content = LoadTemplate("surface_varying.glsl");
	os << "#define VARYING in\n" << content << '\n';
}

void ShaderGenerator::EmitFragmentOutputs(std::ostringstream& os) const
{
	if (m_Outputs.empty())
		return;

	os << "// Fragment outputs\n";
	int colorIndex = 0;
	for (const auto& o : m_Outputs)
	{
		if (o.target != MaterialBuilder::OutputTarget::COLOR)
			continue;

		const char* glslType = "vec4";
		const char* fieldTypeStr = "float4";
		switch (o.type)
		{
		case MaterialBuilder::OutputType::FLOAT:  glslType = "float"; fieldTypeStr = "float";  break;
		case MaterialBuilder::OutputType::FLOAT2: glslType = "vec2";  fieldTypeStr = "float2"; break;
		case MaterialBuilder::OutputType::FLOAT3: glslType = "vec3";  fieldTypeStr = "float3"; break;
		case MaterialBuilder::OutputType::FLOAT4: glslType = "vec4";  fieldTypeStr = "float4"; break;
		}

		int idx = colorIndex++;
		os << "layout(location = " << idx << ") out " << glslType << " " << o.name << ";\n";
		os << "#define FRAG_OUTPUT" << idx << " " << o.name << "\n";
		os << "#define FRAG_OUTPUT_AT" << idx << "\n";
		os << "#define FRAG_OUTPUT_MATERIAL_TYPE" << idx << " " << glslType << "\n";
		os << "#define FRAG_OUTPUT_SWIZZLE" << idx << " " << o.name << "\n";
		os << "#define FRAG_OUTPUT_PRECISION" << idx << "\n";
	}
	os << '\n';
}

std::string ShaderGenerator::MainTemplate(Stage stage, MaterialPass pass) const
{
	if (stage == Stage::Vertex)
	{
		switch (pass)
		{
		case MaterialPass::Depth:    return "surface_depth_main.vs";
		case MaterialPass::Surface:  return (m_Pipeline == Pipeline::FORWARD)
		                            ? "surface_forward_main.vs"
		                            : "surface_deferred_main.vs";
		case MaterialPass::Lighting: return "surface_shading_main.vs";
		}
	}
	else
	{
		switch (pass)
		{
		case MaterialPass::Depth:    return "surface_depth_main.fs";
		case MaterialPass::Surface:  return (m_Pipeline == Pipeline::FORWARD)
		                            ? "surface_forward_main.fs"
		                            : "surface_deferred_main.fs";
		case MaterialPass::Lighting: return "surface_shading_main.fs";
		}
	}
	return {};
}

// =============================================================================
// Constructor
// =============================================================================

ShaderGenerator::ShaderGenerator(
	std::string const& materialName,
	Pipeline pipeline, Shading shadingModel, MaterialDomain domain,
	BufferInterfaceBlock const& materialUib, SamplerInterfaceBlock const& materialSib,
	RHI::AttributeBitset const& requiredAttributes,
	MaterialBuilder::PropertyList const& properties,
	MaterialBuilder::VariableList const& variables,
	MaterialBuilder::OutputList const& outputs,
	MaterialBuilder::PreprocessorDefineList const& defines,
	MaterialBuilder::PushConstantList const& pushConstants,
	std::string const& fragmentCode, size_t fragmentLineOffset,
	std::string const& vertexCode, size_t vertexLineOffset)
	: m_MaterialName(materialName)
	, m_Properties()
	, m_Pipeline(pipeline)
	, m_ShadingModel(shadingModel)
	, m_MaterialDomain(domain)
	, m_MaterialUib(&materialUib)
	, m_MaterialSib(&materialSib)
	, m_RequiredAttributes(requiredAttributes)
	, m_Defines(defines)
	, m_PushConstants(pushConstants)
{
	std::copy(std::begin(properties), std::end(properties), std::begin(m_Properties));

	std::copy(std::begin(variables), std::end(variables), std::begin(m_Variables));
	std::copy(std::begin(outputs), std::end(outputs), std::back_inserter(m_Outputs));

	m_MaterialFragmentCode = fragmentCode;
	m_MaterialVertexCode = vertexCode;
	m_IsMaterialVertexShaderEmpty = vertexCode.empty();

	if (m_MaterialFragmentCode.empty())
	{
		if (m_MaterialDomain == MaterialDomain::SURFACE)
			m_MaterialFragmentCode = "void material(inout MaterialInputs m) {\n    prepareMaterial(m);\n}\n";
		else if (m_MaterialDomain == MaterialDomain::POST_PROCESS)
			m_MaterialFragmentCode = "void postProcess(inout PostProcessInputs p) {\n}\n";
		else if (m_MaterialDomain == MaterialDomain::COMPUTE)
			m_MaterialFragmentCode = "void compute() {\n}\n";
	}

	if (m_MaterialVertexCode.empty())
	{
		if (m_MaterialDomain == MaterialDomain::SURFACE)
			m_MaterialVertexCode = "void materialVertex(inout MaterialVertexInputs m) {\n}\n";
		else if (m_MaterialDomain == MaterialDomain::POST_PROCESS)
			m_MaterialVertexCode = "void postProcessVertex(inout PostProcessVertexInputs m) {\n}\n";
	}
}

// =============================================================================
// Surface-domain dispatch
// =============================================================================

std::string ShaderGenerator::GenerateShader(Stage stage, MaterialPass pass,
                                            const std::string& userCode) const
{
	switch (stage)
	{
	case Stage::Vertex:
		switch (pass)
		{
		case MaterialPass::Depth:    return GenDepthVS(userCode);
		case MaterialPass::Surface:  return GenSurfaceVS(userCode);
		case MaterialPass::Lighting: return GenLightingVS(userCode);
		}
		break;

	case Stage::Fragment:
		switch (pass)
		{
		case MaterialPass::Depth:    return GenDepthFS(userCode);
		case MaterialPass::Surface:  return GenSurfaceFS(userCode);
		case MaterialPass::Lighting: return GenLightingFS(userCode);
		}
		break;

	case Stage::Compute:
		return GenerateComputeShader(userCode);
	}
	return {};
}

std::string ShaderGenerator::GeneratePostProcessShader(Stage stage,
                                                       const std::string& userCode) const
{
	switch (stage)
	{
	case Stage::Vertex:   return GenPostProcessVS(userCode);
	case Stage::Fragment: return GenPostProcessFS(userCode);
	default: return {};
	}
}

// =============================================================================
// Depth — Vertex
// =============================================================================

std::string ShaderGenerator::GenDepthVS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);
	os << '\n';

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define VERTEX_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';

	EmitVertexInputs(os);
	EmitVaryingOut(os);

	for (auto& file : Provider::GetDepthVertex())
		os << LoadTemplate(file) << '\n';

	os << LoadTemplate("common_getter.glsl") << '\n';
	cg.generateVaryingDeclarations(os, m_Variables, "out");

	if (!code.empty())
		os << "// User vertex code\n" << code << '\n';

	os << LoadTemplate(MainTemplate(Stage::Vertex, MaterialPass::Depth)) << '\n';
	return os.str();
}

// =============================================================================
// Depth — Fragment
// =============================================================================

std::string ShaderGenerator::GenDepthFS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define FRAGMENT_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	EmitVaryingIn(os);
	os << LoadTemplate("surface_material_input.fs") << '\n';
	os << LoadTemplate("surface_instancing.glsl") << '\n';

	if (!code.empty())
		os << "// User fragment code\n" << code << '\n';

	os << LoadTemplate(MainTemplate(Stage::Fragment, MaterialPass::Depth)) << '\n';
	return os.str();
}

// =============================================================================
// Surface — Vertex
// =============================================================================

std::string ShaderGenerator::GenSurfaceVS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);
	os << '\n';

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define VERTEX_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';

	EmitVertexInputs(os);
	EmitVaryingOut(os);

	for (auto& file : Provider::GetGBufferVertex())
		os << LoadTemplate(file) << '\n';

	os << LoadTemplate("common_getter.glsl") << '\n';
	cg.generateVaryingDeclarations(os, m_Variables, "out");

	if (!code.empty())
		os << "// User vertex code\n" << code << '\n';

	os << LoadTemplate(MainTemplate(Stage::Vertex, MaterialPass::Surface)) << '\n';
	return os.str();
}

// =============================================================================
// Surface — Fragment
// =============================================================================

std::string ShaderGenerator::GenSurfaceFS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define FRAGMENT_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';
	os << LoadTemplate("common_shading.glsl") << '\n';

	EmitVaryingIn(os);

	os << LoadTemplate("surface_instancing.glsl") << '\n';
	os << LoadTemplate("surface_material_input.fs") << '\n';

	{
		auto content = LoadTemplate("surface_getters.fs");
		if (!content.empty())
			os << content << '\n';
	}

	os << LoadTemplate("common_getter.glsl") << '\n';
	os << LoadTemplate("surface_shading_parameters.fs") << '\n';
	cg.generateVaryingDeclarations(os, m_Variables, "in");
	EmitFragmentOutputs(os);

	if (!code.empty())
		os << "// User fragment code\n" << code << '\n';

	os << LoadTemplate(MainTemplate(Stage::Fragment, MaterialPass::Surface)) << '\n';
	return os.str();
}

// =============================================================================
// Lighting — Vertex (fullscreen triangle)
// =============================================================================

std::string ShaderGenerator::GenLightingVS(const std::string&) const
{
	std::ostringstream os;

	EmitLightHeader(os);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define VERTEX_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate(MainTemplate(Stage::Vertex, MaterialPass::Lighting)) << '\n';
	return os.str();
}

// =============================================================================
// Lighting — Fragment
// =============================================================================

std::string ShaderGenerator::GenLightingFS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define LIGHTING_PASS\n";
	os << "#define FRAGMENT_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';
	os << LoadTemplate("common_shading.glsl") << '\n';
	os << LoadTemplate("surface_material_input.fs") << '\n';
	os << LoadTemplate("lighting_uniforms.glsl") << '\n';

	// IBL samplers — PER_VIEW descriptor set (ues )
	if (m_ShadingModel == Shading::LIT)
	{
		SamplerInterfaceBlock::SamplerInfoList iblSamplers = {
			{"irradianceMap", "irradianceMap", +PerViewBindingPoints::IBL_IRRADIANCE,
			 RHI::SamplerType::SAMPLER_CUBEMAP, RHI::SamplerFormat::FLOAT, false},
			{"prefilterMap", "prefilterMap", +PerViewBindingPoints::IBL_PREFILTER,
			 RHI::SamplerType::SAMPLER_CUBEMAP, RHI::SamplerFormat::FLOAT, false},
			{"brdfLut", "brdfLut", +PerViewBindingPoints::BRDF_LUT,
			 RHI::SamplerType::SAMPLER_2D, RHI::SamplerFormat::FLOAT, false},
		};
		cg.generateCommonSamplers(os, iblSamplers);
	}

	// GBuffer samplers — G_BUFFER descriptor set (auto bindings)
	{
		SamplerInterfaceBlock::SamplerInfoList gbufferSamplers = {
			{"gDepth", "gDepth", +GBufferBindingPoint::G_BUFFER_DEPTH,
			 RHI::SamplerType::SAMPLER_2D, RHI::SamplerFormat::FLOAT, false},
			{"gNormal", "gNormal", +GBufferBindingPoint::G_BUFFER_NORMAL,
			 RHI::SamplerType::SAMPLER_2D, RHI::SamplerFormat::FLOAT, false},
			{"gAlbedo", "gAlbedo", +GBufferBindingPoint::G_BUFFER_ALBEDO,
			 RHI::SamplerType::SAMPLER_2D, RHI::SamplerFormat::FLOAT, false},
			{"gMaterial", "gMaterial", +GBufferBindingPoint::G_BUFFER_MATERIAL,
			 RHI::SamplerType::SAMPLER_2D, RHI::SamplerFormat::FLOAT, false},
		};
		cg.generateCommonSamplers(os, gbufferSamplers);
	}

	os << LoadTemplate("surface_shading_parameters.fs") << '\n';

	if (!code.empty())
		os << "// User fragment code\n" << code << '\n';

	os << LoadTemplate("surface_shading_unlit.fs") << '\n';
	os << LoadTemplate("surface_shading_lit.fs") << '\n';
	os << LoadTemplate(MainTemplate(Stage::Fragment, MaterialPass::Lighting)) << '\n';
	return os.str();
}

// =============================================================================
// PostProcess — Vertex
// =============================================================================

std::string ShaderGenerator::GenPostProcessVS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitLightHeader(os);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define VERTEX_STAGE\n";
	os << "#define ATTRIBUTE in\n";
	os << "#define LOCATION_POSITION 0\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';

	cg.generateVaryingDefines(os, m_Variables);

	for (auto& file : Provider::GetPostProcessVertex())
		os << LoadTemplate(file) << '\n';

	if (!code.empty())
		os << "// User vertex code\n" << code << '\n';

	cg.generateVaryingDeclarations(os, m_Variables, "out");
	os << LoadTemplate("post_process_main.vs") << '\n';
	return os.str();
}

// =============================================================================
// PostProcess — Fragment
// =============================================================================

std::string ShaderGenerator::GenPostProcessFS(const std::string& code) const
{
	std::ostringstream os;
	CodeGenerator cg;

	EmitHeader(os, cg);

	if (m_TargetVulkan)
		os << "#define TARGET_VULKAN_ENVIRONMENT\n";
	os << "#define FRAGMENT_STAGE\n\n";

	os << LoadTemplate("common_defines.glsl") << '\n';
	os << LoadTemplate("common_math.glsl") << '\n';

	EmitFragmentOutputs(os);
	os << LoadTemplate("post_process_inputs.fs") << '\n';

	cg.generateVaryingDeclarations(os, m_Variables, "in");

	if (!code.empty())
		os << "// User fragment code\n" << code << '\n';

	os << LoadTemplate("post_process_main.fs") << '\n';
	return os.str();
}

// =============================================================================
// Compute (stub)
// =============================================================================

std::string ShaderGenerator::GenerateComputeShader(const std::string&) const
{
	return {};
}
